_wandb:
    value:
        cli_version: 0.23.1
        e:
            igj2q8log1q4g8jwsoacfytqmkyrzdkz:
                codePath: upload_data.py
                codePathLocal: upload_data.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "510989955072"
                        used: "261888729088"
                email: kokrhui.ong@gmail.com
                executable: C:\Users\HP\Documents\repos\mlops-weights-&-biases\venv\Scripts\python.exe
                git:
                    commit: 70201da4be040da784f364d5ff4cd7f1704cb096
                    remote: https://github.com/ONGKOKRHUI/mlops-weights---biases-mlflow.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-c572972b-5d64-d032-47e1-06a715da7990
                host: LAPTOP-1TMQC35K
                memory:
                    total: "16390750208"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\HP\Documents\repos\mlops-weights-&-biases\upload_data.py
                python: CPython 3.13.9
                root: C:\Users\HP\Documents\repos\mlops-weights-&-biases
                startedAt: "2026-01-01T09:32:54.692135Z"
                writerId: igj2q8log1q4g8jwsoacfytqmkyrzdkz
        m: []
        python_version: 3.13.9
        t:
            "3":
                - 2
                - 13
            "4": 3.13.9
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
